name: monolith/demo
title: Демонстрационная тема
locale: ru # Язык по умолчанию
sites: [1]
description: Twenty Sixteen — современная версия популярного дизайна для WordPress.
    | Горизонтальный заголовок с дополнительной правой панелью идеально подходит для блогов и сайтов.
    | В теме есть произвольная настройка цветов с красивыми встроенными схемами и гармоничная растяжимая сетка с ориентацией на мобильные устройства,
    | внимание уделено даже мельчайшим деталям. С Twenty Sixteen ваш сайт будет прекрасно выглядеть на любых экранах.
version: 0.1
developer: Petr Petrov
license: MIT
regions: # Описание областей вывода в шаблонах, которые применяются в теме оформления.
    main_menu:
        title: Главное меню
        inheritance: [ 'root', 'main_menu' ] # Включить наследование в папках в случае автоматического создания областей.
    breadcrumbs: Хлебные крошки
    footer: Футер
modules: # Шаблоны для модулей
    Unicat:
        catalog: Каталог
        news: Новости
    Breadcrumbs:
        test: проверочный шаблон
structure: # Предлагать создать следующую структуру при установке на пустой сайт
    title: Главная
    children: # Служебный параметр в котором описываются внутренние разделы
        services:
            title: Услуги
            children:
                design: Дизайн
                seo: Продвижение
        news: Новости
        contacts: Контакты
        about: О компании
